[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#070B17"
secondaryBackgroundColor = "#11182B"
textColor = "#F8FAFC"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
